
package com.container.epcglobal.epcis.wsdl._1;

import com.container.epcglobal.epcis_query.xsd._1.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EPCISServicePortType", targetNamespace = "urn:epcglobal:epcis:wsdl:1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.container.org.unece.cefact.namespaces.standardbusinessdocumentheader.ObjectFactory.class,
    com.container.epcglobal.epcis_query.xsd._1.ObjectFactory.class,
    com.container.epcglobal.epcis.xsd._1.ObjectFactory.class,
    com.container.epcglobal.xsd._1.ObjectFactory.class
})
public interface EPCISServicePortType {


    /**
     * 
     * @param parms
     * @return
     *     returns epcglobal.epcis_query.xsd._1.ArrayOfString
     * @throws SecurityExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws ValidationExceptionResponse
     */
    @WebMethod
    @WebResult(name = "GetQueryNamesResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getQueryNamesReturn")
    public ArrayOfString getQueryNames(
        @WebParam(name = "GetQueryNames", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
                EmptyParms parms)
        throws ImplementationExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse
    ;

    /**
     * 
     * @param parms
     * @return
     *     returns epcglobal.epcis_query.xsd._1.VoidHolder
     * @throws SecurityExceptionResponse
     * @throws QueryTooComplexExceptionResponse
     * @throws DuplicateSubscriptionExceptionResponse
     * @throws InvalidURIExceptionResponse
     * @throws SubscriptionControlsExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws NoSuchNameExceptionResponse
     * @throws SubscribeNotPermittedExceptionResponse
     * @throws QueryParameterExceptionResponse
     * @throws ValidationExceptionResponse
     */
    @WebMethod
    @WebResult(name = "SubscribeResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "subscribeReturn")
    public VoidHolder subscribe(
        @WebParam(name = "Subscribe", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
                Subscribe parms)
        throws DuplicateSubscriptionExceptionResponse, ImplementationExceptionResponse, InvalidURIExceptionResponse, NoSuchNameExceptionResponse, QueryParameterExceptionResponse, QueryTooComplexExceptionResponse, SecurityExceptionResponse, SubscribeNotPermittedExceptionResponse, SubscriptionControlsExceptionResponse, ValidationExceptionResponse
    ;

    /**
     * 
     * @param parms
     * @return
     *     returns epcglobal.epcis_query.xsd._1.VoidHolder
     * @throws SecurityExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws ValidationExceptionResponse
     * @throws NoSuchSubscriptionExceptionResponse
     */
    @WebMethod
    @WebResult(name = "UnsubscribeResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "unsubscribeReturn")
    public VoidHolder unsubscribe(
        @WebParam(name = "Unsubscribe", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
                Unsubscribe parms)
        throws ImplementationExceptionResponse, NoSuchSubscriptionExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse
    ;

    /**
     * 
     * @param parms
     * @return
     *     returns epcglobal.epcis_query.xsd._1.ArrayOfString
     * @throws SecurityExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws NoSuchNameExceptionResponse
     * @throws ValidationExceptionResponse
     */
    @WebMethod
    @WebResult(name = "GetSubscriptionIDsResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getSubscriptionIDsReturn")
    public ArrayOfString getSubscriptionIDs(
        @WebParam(name = "GetSubscriptionIDs", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
        GetSubscriptionIDs parms)
        throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse
    ;

    /**
     * 
     * @param parms
     * @return
     *     returns epcglobal.epcis_query.xsd._1.QueryResults
     * @throws SecurityExceptionResponse
     * @throws QueryTooComplexExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws NoSuchNameExceptionResponse
     * @throws QueryParameterExceptionResponse
     * @throws QueryTooLargeExceptionResponse
     * @throws ValidationExceptionResponse
     */
    @WebMethod
    @WebResult(name = "QueryResults", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "pollReturn")
    public QueryResults poll(
        @WebParam(name = "Poll", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
        Poll parms)
        throws ImplementationExceptionResponse, NoSuchNameExceptionResponse, QueryParameterExceptionResponse, QueryTooComplexExceptionResponse, QueryTooLargeExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse
    ;

    /**
     * 
     * @param parms
     * @return
     *     returns java.lang.String
     * @throws SecurityExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws ValidationExceptionResponse
     */
    @WebMethod
    @WebResult(name = "GetStandardVersionResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getStandardVersionReturn")
    public String getStandardVersion(
        @WebParam(name = "GetStandardVersion", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
        EmptyParms parms)
        throws ImplementationExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse
    ;

    /**
     * 
     * @param parms
     * @return
     *     returns java.lang.String
     * @throws SecurityExceptionResponse
     * @throws ImplementationExceptionResponse
     * @throws ValidationExceptionResponse
     */
    @WebMethod
    @WebResult(name = "GetVendorVersionResult", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "getVendorVersionReturn")
    public String getVendorVersion(
        @WebParam(name = "GetVendorVersion", targetNamespace = "urn:epcglobal:epcis-query:xsd:1", partName = "parms")
        EmptyParms parms)
        throws ImplementationExceptionResponse, SecurityExceptionResponse, ValidationExceptionResponse
    ;

}
