
package com.container.epcglobal.epcis.wsdl._1;

import com.container.epcglobal.epcis_query.xsd._1.QueryTooComplexException;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QueryTooComplexException", targetNamespace = "urn:epcglobal:epcis-query:xsd:1")
public class QueryTooComplexExceptionResponse
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QueryTooComplexException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public QueryTooComplexExceptionResponse(String message, QueryTooComplexException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public QueryTooComplexExceptionResponse(String message, QueryTooComplexException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: epcglobal.epcis_query.xsd._1.QueryTooComplexException
     */
    public QueryTooComplexException getFaultInfo() {
        return faultInfo;
    }

}
